services:
  - type: web
    name: vikitoria-bot
    env: python
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: PORT
        value: 10000
    plan: free
    autoDeploy: true
